### ISSUE TITLE
Create a means to control the order of triggering of listeners.

### ISSUE THREAD

**Issue by obuchtala** [substance/substance-legacy#375]
For example, we have the problem, that surfaces should render a selection after document changes,
but this happens before the nodes are updated, as a surface is created and registered before any node UI.

**Comment by obuchtala** [comment]
Done via 2ded3e9b61234c707d44855afaefb3c2214842e6

**Comment by michael** [comment]
It works, but i still get a warning when changing the text type.

Could not find DOM element for path ["heading_231f71ca0c09c9d8ee3ffa81c345c6b7", "content"]

Not sure what is causing that, i check later
